from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt


# Project paths
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data" / "processed"
OUTPUT_DIR = PROJECT_ROOT / "reports"

OUTPUT_DIR.mkdir(exist_ok=True)


# Load customer, order, and payment data
customers = pd.read_csv(DATA_DIR / "customers.csv")
orders = pd.read_csv(DATA_DIR / "orders.csv")
payments = pd.read_csv(DATA_DIR / "payments.csv")


# Count orders for each actual customer.
# customer_unique_id identifies the same customer across records.
customer_orders = (
    orders.merge(
        customers[["customer_id", "customer_unique_id"]],
        on="customer_id",
        how="inner",
    )
    .groupby("customer_unique_id", as_index=False)
    .agg(order_count=("order_id", "nunique"))
)

customer_orders["customer_type"] = customer_orders["order_count"].apply(
    lambda count: "One-time" if count == 1 else "Repeat"
)


# Summarize one-time and repeat customers
customer_summary = (
    customer_orders.groupby("customer_type", as_index=False)
    .agg(
        customers=("customer_unique_id", "count"),
        average_orders=("order_count", "mean"),
    )
)

customer_summary["average_orders"] = customer_summary[
    "average_orders"
].round(2)


# Calculate revenue for each customer
order_payments = (
    payments.groupby("order_id", as_index=False)["payment_value"]
    .sum()
    .rename(columns={"payment_value": "order_value"})
)

customer_revenue = (
    orders.merge(
        customers[["customer_id", "customer_unique_id"]],
        on="customer_id",
        how="inner",
    )
    .merge(
        order_payments,
        on="order_id",
        how="inner",
    )
    .groupby("customer_unique_id", as_index=False)
    .agg(total_revenue=("order_value", "sum"))
)

customer_analysis = customer_orders.merge(
    customer_revenue,
    on="customer_unique_id",
    how="left",
)

customer_analysis["total_revenue"] = customer_analysis[
    "total_revenue"
].fillna(0)


# Compare revenue generated by one-time and repeat customers
revenue_summary = (
    customer_analysis.groupby("customer_type", as_index=False)
    .agg(
        customers=("customer_unique_id", "count"),
        average_revenue_per_customer=("total_revenue", "mean"),
        total_revenue=("total_revenue", "sum"),
    )
)

revenue_summary["average_revenue_per_customer"] = revenue_summary[
    "average_revenue_per_customer"
].round(2)

revenue_summary["total_revenue"] = revenue_summary[
    "total_revenue"
].round(2)


# Save customer analysis results
customer_summary.to_csv(
    OUTPUT_DIR / "customer_summary.csv",
    index=False,
)

revenue_summary.to_csv(
    OUTPUT_DIR / "customer_revenue.csv",
    index=False,
)


# Plot one-time vs repeat customers
plt.figure(figsize=(8, 5))

plt.bar(
    customer_summary["customer_type"],
    customer_summary["customers"],
)

plt.title("One-Time vs Repeat Customers")
plt.xlabel("Customer Type")
plt.ylabel("Customers")
plt.tight_layout()

plt.savefig(
    OUTPUT_DIR / "customer_types.png",
    dpi=150,
)

plt.close()


print("Customer analysis completed.")
print(f"Customer summary saved to: {OUTPUT_DIR / 'customer_summary.csv'}")
print(f"Revenue analysis saved to: {OUTPUT_DIR / 'customer_revenue.csv'}")
print(f"Customer chart saved to: {OUTPUT_DIR / 'customer_types.png'}")