-- ============================================================
-- SALES PERFORMANCE
-- ============================================================

-- Monthly revenue, order count, and average order value.
-- Payments are aggregated by order first so multiple payment
-- records for one order do not distort the order-level metrics.

WITH order_payments AS (
    SELECT
        order_id,
        SUM(payment_value) AS order_value
    FROM payments
    GROUP BY order_id
)
SELECT
    DATE_TRUNC('month', o.order_purchase_timestamp)::date AS month,
    COUNT(DISTINCT o.order_id) AS orders,
    ROUND(SUM(op.order_value), 2) AS revenue,
    ROUND(AVG(op.order_value), 2) AS average_order_value
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY month
ORDER BY month;


-- ============================================================
-- OVERALL ORDER VALUE
-- ============================================================

-- Calculates order-level average, minimum, and maximum value.
-- Payment records are aggregated first because one order can
-- have multiple payment records.

WITH order_values AS (
    SELECT
        order_id,
        SUM(payment_value) AS order_value
    FROM payments
    GROUP BY order_id
)
SELECT
    ROUND(AVG(order_value), 2) AS average_order_value,
    ROUND(MIN(order_value), 2) AS minimum_order_value,
    ROUND(MAX(order_value), 2) AS maximum_order_value
FROM order_values;


-- ============================================================
-- PAYMENT ANALYSIS
-- ============================================================

-- Payment method usage, total payment value, and average
-- payment value.

SELECT
    payment_type,
    COUNT(*) AS payment_count,
    ROUND(SUM(payment_value), 2) AS total_payment_value,
    ROUND(AVG(payment_value), 2) AS average_payment_value
FROM payments
GROUP BY payment_type
ORDER BY total_payment_value DESC;


-- Payment installment usage and payment value.

SELECT
    payment_installments,
    COUNT(*) AS payment_count,
    ROUND(AVG(payment_value), 2) AS average_payment_value,
    ROUND(SUM(payment_value), 2) AS total_payment_value
FROM payments
GROUP BY payment_installments
ORDER BY payment_installments;


-- Payment method and installment usage.
-- Installments are primarily associated with credit card payments.

SELECT
    payment_type,
    payment_installments,
    COUNT(*) AS payment_count,
    ROUND(AVG(payment_value), 2) AS average_payment_value
FROM payments
GROUP BY
    payment_type,
    payment_installments
ORDER BY
    payment_type,
    payment_installments;


-- ============================================================
-- CUSTOMER ANALYSIS
-- ============================================================

-- One-time vs repeat customers.
-- customer_unique_id identifies the actual customer across
-- multiple customer records and orders.

WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS order_count
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
)
SELECT
    COUNT(*) AS total_customers,
    COUNT(*) FILTER (
        WHERE order_count = 1
    ) AS one_time_customers,
    COUNT(*) FILTER (
        WHERE order_count > 1
    ) AS repeat_customers
FROM customer_orders;


-- Distribution of customers by number of orders.

WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS order_count
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
)
SELECT
    order_count,
    COUNT(*) AS customer_count
FROM customer_orders
GROUP BY order_count
ORDER BY order_count;


-- Revenue generated by one-time and repeat customers.

WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS order_count
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
)
SELECT
    CASE
        WHEN co.order_count = 1 THEN 'One-time'
        ELSE 'Repeat'
    END AS customer_type,
    COUNT(DISTINCT co.customer_unique_id) AS customers,
    ROUND(SUM(p.payment_value), 2) AS total_revenue,
    ROUND(AVG(p.payment_value), 2) AS average_payment_value
FROM customer_orders co
JOIN customers c
    ON co.customer_unique_id = c.customer_unique_id
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN payments p
    ON o.order_id = p.order_id
GROUP BY customer_type
ORDER BY total_revenue DESC;


-- Average revenue generated per customer type.

WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS order_count
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
),
customer_revenue AS (
    SELECT
        co.customer_unique_id,
        co.order_count,
        SUM(p.payment_value) AS total_revenue
    FROM customer_orders co
    JOIN customers c
        ON co.customer_unique_id = c.customer_unique_id
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN payments p
        ON o.order_id = p.order_id
    GROUP BY
        co.customer_unique_id,
        co.order_count
)
SELECT
    CASE
        WHEN order_count = 1 THEN 'One-time'
        ELSE 'Repeat'
    END AS customer_type,
    COUNT(*) AS customers,
    ROUND(AVG(total_revenue), 2) AS average_revenue_per_customer,
    ROUND(SUM(total_revenue), 2) AS total_revenue
FROM customer_revenue
GROUP BY customer_type
ORDER BY average_revenue_per_customer DESC;


-- ============================================================
-- PRODUCT CATEGORY ANALYSIS
-- ============================================================

-- Revenue, order volume, item volume, and average item price
-- by product category.
-- Categories without a name are excluded.

SELECT
    p.product_category_name,
    COUNT(DISTINCT oi.order_id) AS orders,
    COUNT(*) AS items_sold,
    ROUND(SUM(oi.price), 2) AS product_revenue,
    ROUND(AVG(oi.price), 2) AS average_item_price
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
WHERE p.product_category_name IS NOT NULL
  AND p.product_category_name <> ''
GROUP BY p.product_category_name
ORDER BY product_revenue DESC;


-- Top categories by number of items sold.

SELECT
    p.product_category_name,
    COUNT(*) AS items_sold,
    COUNT(DISTINCT oi.order_id) AS orders,
    ROUND(SUM(oi.price), 2) AS product_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
WHERE p.product_category_name IS NOT NULL
  AND p.product_category_name <> ''
GROUP BY p.product_category_name
ORDER BY items_sold DESC
LIMIT 15;


-- Categories with the highest average item price.
-- A minimum of 100 items avoids results based on very small samples.

SELECT
    p.product_category_name,
    COUNT(*) AS items_sold,
    ROUND(AVG(oi.price), 2) AS average_item_price,
    ROUND(SUM(oi.price), 2) AS product_revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
WHERE p.product_category_name IS NOT NULL
  AND p.product_category_name <> ''
GROUP BY p.product_category_name
HAVING COUNT(*) >= 100
ORDER BY average_item_price DESC
LIMIT 15;


-- ============================================================
-- DELIVERY PERFORMANCE
-- ============================================================

-- Average, fastest, and longest delivery time for completed orders.

SELECT
    ROUND(AVG(delivery_days), 2) AS average_delivery_days,
    ROUND(MIN(delivery_days), 2) AS fastest_delivery_days,
    ROUND(MAX(delivery_days), 2) AS longest_delivery_days
FROM orders
WHERE order_status = 'delivered'
  AND delivery_days IS NOT NULL;


-- Percentage of delivered orders that arrived on time or late.
-- A delivery delay <= 0 means the order arrived on or before
-- the estimated delivery date.

SELECT
    COUNT(*) AS delivered_orders,
    COUNT(*) FILTER (
        WHERE delivery_delay_days <= 0
    ) AS delivered_on_time,
    COUNT(*) FILTER (
        WHERE delivery_delay_days > 0
    ) AS delivered_late,
    ROUND(
        100.0 * COUNT(*) FILTER (
            WHERE delivery_delay_days <= 0
        ) / NULLIF(COUNT(*), 0),
        2
    ) AS on_time_percentage,
    ROUND(
        100.0 * COUNT(*) FILTER (
            WHERE delivery_delay_days > 0
        ) / NULLIF(COUNT(*), 0),
        2
    ) AS late_percentage
FROM orders
WHERE order_status = 'delivered'
  AND delivery_delay_days IS NOT NULL;


-- Delivery performance by product category.
-- Each order is evaluated once per category to avoid weighting
-- orders with multiple items more heavily.

WITH category_orders AS (
    SELECT DISTINCT
        o.order_id,
        p.product_category_name,
        o.delivery_days,
        o.delivery_delay_days
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    WHERE o.order_status = 'delivered'
      AND o.delivery_days IS NOT NULL
      AND p.product_category_name IS NOT NULL
      AND p.product_category_name <> ''
)
SELECT
    product_category_name,
    COUNT(*) AS delivered_orders,
    ROUND(AVG(delivery_days), 2) AS average_delivery_days,
    ROUND(
        100.0 * COUNT(*) FILTER (
            WHERE delivery_delay_days <= 0
        ) / NULLIF(COUNT(*), 0),
        2
    ) AS on_time_percentage
FROM category_orders
GROUP BY product_category_name
ORDER BY average_delivery_days;